# [source.crates-io]
# replace-with = "vendored-sources"
# 
# [source.vendored-sources]
# directory = "vendor"

# [target.x86_64-pc-windows-msvc]
# rustflags = ["-C", "target-feature=+crt-static"]
# # # cargo rustc -q -- --print=native-static-libs
# [build]
# rustflags = ["-C", "target-feature=+crt-static"]
